context:
  version: "0.77.0"

package:
  name: nono
  version: ${{ version }}

source:
  url: https://github.com/nolabs-ai/nono/archive/refs/tags/v${{ version }}.tar.gz
  sha256: beed01f90f54f49877eedc8d87341f18308bf07cff1cb89c8dd290f9c34ba281

build:
  number: 0
  skip: win
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - if: unix
        then:
          # Tell `pixi global` to not set CONDA_PREFIX during activation
          # https://pixi.sh/dev/global_tools/introduction/#opt-out-of-conda_prefix
          - mkdir -p "${PREFIX}/etc/pixi/nono"
          - touch "${PREFIX}/etc/pixi/nono/global-ignore-conda-prefix"
          - cargo auditable install --locked --no-track --bins --root ${{ PREFIX }} --path crates/nono-cli
        else:
          - mkdir "%PREFIX%\etc\pixi\nono"
          - type nul > "%PREFIX%\etc\pixi\nono\global-ignore-conda-prefix"
          - cargo auditable install --locked --no-track --bins --root %LIBRARY_PREFIX% --path crates/nono-cli
      - cargo-bundle-licenses --format yaml --output ./THIRDPARTY.yml

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - cargo-auditable
    - pkg-config
  host:
    - dbus

tests:
  - script: nono --help
  - package_contents:
      bin:
        - nono
      files:
        - etc/pixi/nono/global-ignore-conda-prefix
      strict: true

about:
  homepage: https://nono.sh/
  summary: Capability-based sandboxing library using Landlock (Linux) and Seatbelt (macOS).
  description: |
    nono provides OS-enforced sandboxing where unauthorized operations are structurally impossible.
    Once a sandbox is applied, there is no API to expand permissions - the kernel enforces all restrictions.
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  documentation: https://nono.sh/docs
  repository: https://github.com/nolabs-ai/nono

extra:
  recipe-maintainers:
    - synapticarbors
